# -*- coding: utf-8 -*-
"""
《我的世界》主题 —— 固件头文件生成器
=====================================================
从 mc_ui_preview.py 提取 5x7 点阵字形表与 12x12 方块图标，
生成 src/mc_theme.h（PROGMEM 数据 + 绘制函数）。

设计稿与固件共用同一份数据源，**绝不手抄位图** —— 改了设计稿重跑本脚本即可。
生成后自带 verify：把写出的 .h 文本重新解析回来，逐值比对，防止生成 bug。

用法：python gen_mc_theme.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import mc_ui_preview as P          # noqa: E402

OUT = os.path.abspath(os.path.join(HERE, '..', 'src', 'mc_theme.h'))
LOG_PATH = os.path.join(HERE, 'gen_mc_theme.log')
LOG = []


def say(msg):
    """同时打印并落盘（本机 PowerShell 会吞 stdout，落盘才看得到结果）"""
    print(msg)
    LOG.append(str(msg))

# 图标顺序：CPU/RAM/NET/GPU/DSK（与设计稿 draw_screen 的行序一致）
ICON_ORDER = ['CPU', 'RAM', 'NET', 'GPU', 'DSK']


def rgb565(rgb):
    """RGB888 -> RGB565，与固件 RGB() 宏完全一致"""
    r, g, b = rgb
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


# ============================================================ 提取字形
glyph_keys, glyph_bytes = [], []
for k, rows in P.F.items():
    if len(k) != 1 or k == ' ':        # 跳过多字符别名('DEG')与空格(用 0xFF 表示)
        continue
    glyph_keys.append(k)
    bs = []
    for row in rows:                   # 7 行 x 5 列
        v = 0
        for i, ch in enumerate(row[:5]):
            if ch == '#':
                v |= (0x10 >> i)       # bit4=最左列
        bs.append(v)
    glyph_bytes.append(bs)

GI = {k: i for i, k in enumerate(glyph_keys)}
N_GLYPH = len(glyph_keys)


def gmap_for(c):
    u = c.upper()
    return GI.get(u, 0xFF)


GMAP = [gmap_for(chr(c)) for c in range(128)]

# ============================================================ 提取图标
ICONS = {}
for k in ICON_ORDER:
    art, pal = P.ICONS[k]
    assert len(art) == 144, '%s 期望 144 像素，实得 %d' % (k, len(art))
    ICONS[k] = [rgb565(pal[art[i]]) for i in range(144)]

# ============================================================ 生成 C 文本
L = []
A = L.append
A('// Auto-generated by tools/gen_mc_theme.py -- DO NOT EDIT BY HAND')
A('// 《我的世界》主题数据 + 绘制函数：5x7 点阵字 %d 个字形 + 12x12 方块图标 %d 个' % (N_GLYPH, len(ICON_ORDER)))
A('// 色值取自 MC 官方调色板（16 色格式化代码 / GUI 灰阶 / 经验条绿）')
A('// ⚠️ 必须放在 sprite 声明之后 include（绘制函数要用 sprite）')
A('#pragma once')
A('')
A('#include <Arduino.h>')
A('')
A('// ---------------------------------------------------------------- 几何')
A('#define MC_GLYPH_W   5')
A('#define MC_GLYPH_H   7')
A('#define MC_GLYPH_ADV 6      // 步进（5 列 + 1 列字距）')
A('#define MC_GLYPH_N   %d' % N_GLYPH)
A('#define MC_ICON_SZ   12     // 方块图标边长')
A('')
A('// ---------------------------------------------------------------- 配色（MC 官方色板）')
A('static const uint16_t MCUI_BLACK   = RGB(0x00, 0x00, 0x00);  // §0')
A('static const uint16_t MCUI_DGRAY   = RGB(0x55, 0x55, 0x55);  // §8 dark_gray')
A('static const uint16_t MCUI_GRAY    = RGB(0xAA, 0xAA, 0xAA);  // §7 gray')
A('static const uint16_t MCUI_WHITE   = RGB(0xFF, 0xFF, 0xFF);  // §f')
A('static const uint16_t MCUI_GREEN   = RGB(0x55, 0xFF, 0x55);  // §a')
A('static const uint16_t MCUI_AQUA    = RGB(0x55, 0xFF, 0xFF);  // §b')
A('static const uint16_t MCUI_BLUE    = RGB(0x55, 0x55, 0xFF);  // §9')
A('static const uint16_t MCUI_GOLD    = RGB(0xFF, 0xAA, 0x00);  // §6')
A('static const uint16_t MCUI_RED     = RGB(0xFF, 0x55, 0x55);  // §c')
A('static const uint16_t MCUI_LPURPLE = RGB(0xFF, 0x55, 0xFF);  // §d')
A('static const uint16_t MCUI_YELLOW  = RGB(0xFF, 0xFF, 0x55);  // §e')
A('static const uint16_t MCUI_XP      = RGB(0x80, 0xFF, 0x20);  // experience_text')
A('')
A('static const uint16_t MCUI_BG      = RGB(0x21, 0x21, 0x21);  // GUI 最深灰阶（屏底）')
A('static const uint16_t MCUI_HEAD    = RGB(0x37, 0x37, 0x37);  // GUI 面板灰（顶栏）')
A('static const uint16_t MCUI_HI      = RGB(0x8B, 0x8B, 0x8B);  // 亮面（上/左）')
A('static const uint16_t MCUI_LO      = RGB(0x15, 0x15, 0x15);  // 暗面（下/右）')
A('static const uint16_t MCUI_SHADOW  = RGB(0x3F, 0x3F, 0x3F);  // 文字右下 1px 投影')
A('static const uint16_t MCUI_SLOT    = RGB(0x2A, 0x2A, 0x2A);  // 物品栏凹槽底')
A('static const uint16_t MCUI_SLOT_HI = RGB(0x14, 0x14, 0x14);  // 凹槽上/左（暗）')
A('static const uint16_t MCUI_SLOT_LO = RGB(0x56, 0x56, 0x56);  // 凹槽下/右（亮）')
A('static const uint16_t MCUI_DOT_LO  = RGB(0x0F, 0x6E, 0x56);  // 选中页码块的下/右')
A('')

# ---- 字形位图
A('// ---------------------------------------------------------------- 5x7 点阵字形')
A('// 每字形 7 字节（一行一字节），只用低 5 位：bit4=最左列 .. bit0=最右列')
chars_desc = ' '.join("'%s'" % k for k in glyph_keys)
A('// 顺序：%s' % chars_desc)
A('static const uint8_t MC_GLYPHS[MC_GLYPH_N][MC_GLYPH_H] PROGMEM = {')
for k, bs in zip(glyph_keys, glyph_bytes):
    A('  {%s},  // %s' % (','.join('0x%02X' % v for v in bs), k))
A('};')
A('')
A('// ASCII 0..127 -> 字形索引；0xFF = 无字形（按空格跳过）。小写自动转大写。')
A('static const uint8_t MC_GMAP[128] PROGMEM = {')
for i in range(0, 128, 16):
    row = ','.join('0x%02X' % GMAP[i + j] for j in range(16))
    tag = ''
    if i == 0x20:
        tag = '  // 0x20 空格起'
    A('  %s,%s' % (row, tag))
A('};')
A('')

# ---- 图标位图
A('// ---------------------------------------------------------------- 12x12 方块图标（RGB565）')
for k in ICON_ORDER:
    A('// %s' % k)
    A('static const uint16_t MC_ICON_%s[144] PROGMEM = {' % k)
    a = ICONS[k]
    for r in range(12):
        A('  %s,' % ','.join('0x%04X' % a[r * 12 + c] for c in range(12)))
    A('};')
    A('')

# ---- 绘制函数
A('''// ---------------------------------------------------------------- 绘制函数
// 逐像素从 PROGMEM 画 5x7 字形。bold = 右侧再补 1 列（MC 主值用的加粗观感）
static void mcGlyph(char c, int x, int y, uint16_t col, int scale, bool bold) {
  uint8_t uc = (uint8_t)c;
  if (uc >= 128) return;
  uint8_t gi = pgm_read_byte(&MC_GMAP[uc]);
  if (gi == 0xFF || gi >= MC_GLYPH_N) return;
  const uint8_t* g = MC_GLYPHS[gi];
  for (int r = 0; r < MC_GLYPH_H; r++) {
    uint8_t bits = pgm_read_byte(&g[r]);
    if (!bits) continue;
    for (int b = 0; b < MC_GLYPH_W; b++) {
      if (!(bits & (0x10 >> b))) continue;
      int px = x + b * scale, py = y + r * scale;
      if (scale == 1) sprite.drawPixel(px, py, col);
      else            sprite.fillRect(px, py, scale, scale, col);
      if (bold) {
        if (scale == 1) sprite.drawPixel(px + 1, py, col);
        else            sprite.fillRect(px + scale, py, scale, scale, col);
      }
    }
  }
}

// 字符串宽度（与设计稿 text_w 一致：末字后不留字距）
static int mcStrW(const char* s, int scale, bool bold) {
  int n = 0; while (s[n]) n++;
  if (n == 0) return 0;
  return n * MC_GLYPH_ADV * scale - scale + (bold ? scale : 0);
}

// 画字符串；(x,y)=左上角。shadow 传 0 表示不画投影（设计稿里投影都不是纯黑，故 0 可作哨兵）
static void mcStr(const char* s, int x, int y, uint16_t col, int scale,
                  uint16_t shadow, bool bold) {
  if (shadow) {
    int cx = x;
    for (const char* p = s; *p; p++) { mcGlyph(*p, cx + scale, y + scale, shadow, scale, bold); cx += MC_GLYPH_ADV * scale; }
  }
  int cx = x;
  for (const char* p = s; *p; p++) { mcGlyph(*p, cx, y, col, scale, bold); cx += MC_GLYPH_ADV * scale; }
}

// 右对齐画字符串（right = 右边界 x）
static void mcStrRight(const char* s, int right, int y, uint16_t col, int scale,
                       uint16_t shadow, bool bold) {
  mcStr(s, right - mcStrW(s, scale, bold), y, col, scale, shadow, bold);
}

// MC 招牌立体边框：上/左=hi，下/右=lo，内部填 fill（1px 边框）
static void mcBevel(int x, int y, int w, int h, uint16_t hi, uint16_t lo, uint16_t fill) {
  sprite.fillRect(x, y, w, h, fill);
  sprite.writeFastHLine(x, y, w, hi);
  sprite.writeFastVLine(x, y, h, hi);
  sprite.writeFastHLine(x, y + h - 1, w, lo);
  sprite.writeFastVLine(x + w - 1, y, h, lo);
}

// 方块图标嵌进 MC 物品栏式凹槽（上/左暗、下/右亮的凹陷边框），占 14x14
static void mcIcon(const uint16_t* art, int x, int y) {
  mcBevel(x, y, MC_ICON_SZ + 2, MC_ICON_SZ + 2, MCUI_SLOT_HI, MCUI_SLOT_LO, MCUI_SLOT);
  for (int r = 0; r < MC_ICON_SZ; r++)
    for (int c = 0; c < MC_ICON_SZ; c++)
      sprite.drawPixel(x + 1 + c, y + 1 + r, pgm_read_word(&art[r * MC_ICON_SZ + c]));
}

// MC 经验条式分段进度条：凹陷槽 + 3px 格 / 1px 间隔
static void mcXpBar(int x, int y, int w, int h, int pct, uint16_t fill) {
  mcBevel(x, y, w, h, MCUI_DGRAY, MCUI_HI, MCUI_BLACK);
  const int cell = 3, gap = 1;
  int iw = w - 2, ih = h - 2;
  int total = (iw + gap) / (cell + gap);          // 总格数
  int on = 0;
  if (pct >= 0) {
    int p = pct > 100 ? 100 : pct;
    on = (int)(total * p / 100.0f + 0.5f);
  }
  for (int i = 0; i < on; i++)
    sprite.fillRect(x + 1 + i * (cell + gap), y + 1, cell, ih, fill);
}

// 总览页每行指标的颜色（沿用原页阈值：>=85% 红、>=60% 黄，越界则用基色）
static uint16_t mcLoadColor(int pct, uint16_t base) {
  if (pct < 0)   return MCUI_GRAY;
  if (pct >= 85) return MCUI_RED;
  if (pct >= 60) return MCUI_YELLOW;
  return base;
}
''')

text = '\n'.join(L) + '\n'
with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
    f.write(text)
say('wrote %s (%d bytes, %d glyphs, %d icons)' % (OUT, len(text.encode('utf-8')), N_GLYPH, len(ICON_ORDER)))

# ============================================================ 自检：把写出的 C 文本解析回来，逐值比对
src = open(OUT, encoding='utf-8').read()


def parse_u8_2d(name):
    m = re.search(r'%s\[[^]]*\]\[[^]]*\]\s*PROGMEM\s*=\s*\{(.*?)\n\};' % name, src, re.S)
    assert m, 'parse fail: ' + name
    out = []
    for line in m.group(1).splitlines():
        line = line.split('//')[0].strip()
        if not line.startswith('{'):
            continue
        out.append([int(v, 16) for v in re.findall(r'0x([0-9A-Fa-f]{2})', line)])
    return out


def _strip_comments(body):
    return '\n'.join(l.split('//')[0] for l in body.splitlines())


def parse_u8_1d(name):
    m = re.search(r'%s\[[^]]*\]\s*PROGMEM\s*=\s*\{(.*?)\n\};' % name, src, re.S)
    assert m, 'parse fail: ' + name
    return [int(v, 16) for v in re.findall(r'0x([0-9A-Fa-f]{2})', _strip_comments(m.group(1)))]


def parse_u16_1d(name):
    m = re.search(r'%s\[[^]]*\]\s*PROGMEM\s*=\s*\{(.*?)\n\};' % name, src, re.S)
    assert m, 'parse fail: ' + name
    return [int(v, 16) for v in re.findall(r'0x([0-9A-Fa-f]{4})', _strip_comments(m.group(1)))]


ok = True
g = parse_u8_2d('MC_GLYPHS')
if g != glyph_bytes:
    ok = False
    say('FAIL: MC_GLYPHS mismatch')
m = parse_u8_1d('MC_GMAP')
if m != GMAP:
    ok = False
    say('FAIL: MC_GMAP mismatch')
for k in ICON_ORDER:
    got = parse_u16_1d('MC_ICON_' + k)
    if got != ICONS[k]:
        ok = False
        say('FAIL: MC_ICON_%s mismatch (%d vs %d)' % (k, len(got), 144))
say('verify: %s' % ('OK 数据与设计稿逐值一致' if ok else 'FAILED'))

with open(LOG_PATH, 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(LOG) + '\n')
sys.exit(0 if ok else 1)
