# -*- coding: utf-8 -*-
"""Generate 16x16 monochrome C bitmaps for Chinese *city-name* glyphs.

Same format as weather_cn.h (SimHei, MSB-first, row-major, 32 bytes/glyph),
plus two helpers used by the weather header:
  - cityCnAllFound(s):  true if every CJK char in s has a glyph (safe to draw)
  - cityCnWidth(s):     total pixel width of s when drawn (for positioning)

The character set is derived from a list of common Chinese city names
(provincial capitals + major cities). Because arbitrary IP locations can
return any city, the firmware falls back to the English name when a glyph
is missing; this set covers the vast majority of users.

Usage:
  python tools/gen_city_cn.py
"""
import os as _pathos
_HERE = _pathos.path.dirname(_pathos.path.abspath(__file__)).replace('\\', '/')
_TOOLS_DIR = _HERE + '/'
_SRC_DIR = _pathos.normpath(_HERE + '/../src').replace('\\', '/') + '/'
_BASE_DIR = _pathos.normpath(_HERE + '/..').replace('\\', '/')

from PIL import Image, ImageDraw, ImageFont

# 常见城市名（去重后取汉字）。覆盖省会 + 主要地级市，绝大多数用户命中。
# [2026-09-16] 补秦巴 / 汉江流域：本机 IP 定位实测落在「安康」（陕西南部），
# 原表只收省会与主要地级市，安康两个字都不在库里 → 城市名只能回退成拼音
# ANKANG（设备端回退路径用 ASCII 字库渲染，中文会画成方块，所以必须收录）。
# 顺带补齐周边常出现的地市，避免换网络后再回退。
CITIES = (
    "北京 天津 上海 重庆 石家庄 太原 呼和浩特 沈阳 长春 哈尔滨 南京 杭州 "
    "合肥 福州 南昌 济南 郑州 武汉 长沙 广州 南宁 海口 成都 贵阳 昆明 拉萨 "
    "西安 兰州 西宁 银川 乌鲁木齐 深圳 青岛 大连 宁波 厦门 苏州 无锡 常州 "
    "徐州 温州 金华 佛山 东莞 珠海 中山 惠州 泉州 烟台 潍坊 洛阳 宜昌 株洲 "
    "唐山 秦皇岛 张家口 保定 大同 包头 鄂尔多斯 鞍山 吉林 齐齐哈尔 大庆 南通 "
    "扬州 镇江 泰州 盐城 绍兴 嘉兴 湖州 衢州 台州 丽水 黄山 马鞍山 铜陵 滁州 "
    "莆田 漳州 龙岩 赣州 九江 上饶 临沂 淄博 威海 商丘 南阳 襄阳 荆州 衡阳 "
    "柳州 桂林 北海 三亚 绵阳 宜宾 泸州 攀枝花 遵义 大理 丽江 宝鸡 咸阳 渭南 "
    "榆林 延安 汉中 天水 酒泉 嘉峪关 敦煌 库尔勒 克拉玛依 石河子 喀什 伊犁 "
    "州 延边 朝鲜 自治 香港 澳门 台湾 "
    "安康 汉阴 商洛 铜川 十堰 恩施 广元 达州 巴中 南充 涪陵 万州 张家界 常德 岳阳"
)
FONT_PATH = r"C:\Windows\Fonts\simhei.ttf"
OUT_H = _SRC_DIR + "cn_city.h"
GLYPH = 16


def uniq_chars():
    seen = []
    for ch in CITIES:
        if ch == " ":
            continue
        if ch not in seen:
            seen.append(ch)
    return "".join(seen)


def render(ch):
    big = GLYPH * 8
    img = Image.new("L", (big, big), 0)
    d = ImageDraw.Draw(img)
    size = int(big * 0.86)
    font = ImageFont.truetype(FONT_PATH, size)
    d.text((big / 2, big / 2), ch, font=font, fill=255, anchor="mm")
    img = img.resize((GLYPH, GLYPH), Image.LANCZOS)
    px = img.load()
    bits = []
    for y in range(GLYPH):
        row = 0
        for x in range(GLYPH):
            if px[x, y] >= 128:
                row |= 1 << (15 - x)
                bits.append("#")
            else:
                bits.append(".")
        yield row
        bits.append("\n")
    print(ch + ":")
    print("".join(bits))


def main():
    CHARS = uniq_chars()
    names = ["CCN_%d" % i for i in range(len(CHARS))]
    lines = []
    lines.append("// Auto-generated by tools/gen_city_cn.py -- 16x16 mono glyphs (SimHei)")
    lines.append("// chars: " + " ".join(CHARS))
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append("#define CCN_W 16")
    lines.append("#define CCN_H 16")
    lines.append("#define CCN_BYTES 32")
    lines.append("")
    lines.append("enum { " + ", ".join(names) + " };")
    lines.append("")
    lines.append("static const uint8_t CCN_GLYPHS[][CCN_BYTES] PROGMEM = {")
    for ch in CHARS:
        rows = list(render(ch))
        body = []
        for r in rows:
            body.append("0x%02X,0x%02X" % ((r >> 8) & 0xFF, r & 0xFF))
        lines.append("  // " + ch)
        lines.append("  {" + ",".join(body) + "},")
    lines.append("};")
    lines.append("")
    lines.append("static const char CCN_T[] PROGMEM = \"" + CHARS + "\";")
    lines.append("static int cityCnFind(const char* u) {")
    lines.append("  for (int i = 0; i < (int)(sizeof(CCN_T) - 1) / 3; i++) {")
    lines.append("    if (u[0] == pgm_read_byte(&CCN_T[i * 3]) &&")
    lines.append("        u[1] == pgm_read_byte(&CCN_T[i * 3 + 1]) &&")
    lines.append("        u[2] == pgm_read_byte(&CCN_T[i * 3 + 2])) return i;")
    lines.append("  }")
    lines.append("  return -1;")
    lines.append("}")
    lines.append("")
    lines.append("// 字符串里每个汉字都在字库里？（须至少含一个汉字；纯 ASCII 返回 false，走英文回退）")
    lines.append("static bool cityCnAllFound(const char* s) {")
    lines.append("  bool any = false;")
    lines.append("  for (const char* p = s; *p; ) {")
    lines.append("    if ((unsigned char)*p >= 0x80) {")
    lines.append("      if (cityCnFind(p) < 0) return false;")
    lines.append("      any = true;")
    lines.append("      p += 3;")
    lines.append("    } else p++;")
    lines.append("  }")
    lines.append("  return any;")
    lines.append("}")
    lines.append("")
    lines.append("static void drawCCn(int idx, int x, int y, uint16_t color) {")
    lines.append("  for (int row = 0; row < CCN_H; row++) {")
    lines.append("    uint16_t bits = (uint16_t)pgm_read_byte(&CCN_GLYPHS[idx][row * 2]) << 8")
    lines.append("                  | pgm_read_byte(&CCN_GLYPHS[idx][row * 2 + 1]);")
    lines.append("    for (int col = 0; col < CCN_W; col++)")
    lines.append("      if (bits & (0x8000 >> col)) sprite.writeFastHLine(x + col, y + row, 1, color);")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("// 在 (x,y) 画一串纯汉字（UTF-8），返回占用宽度（含字间距）")
    lines.append("static int drawCityCn(const char* s, int x, int y, uint16_t color, int pad = 2) {")
    lines.append("  int cx = x;")
    lines.append("  for (const char* p = s; *p; ) {")
    lines.append("    if ((unsigned char)*p >= 0x80) {")
    lines.append("      int idx = cityCnFind(p);")
    lines.append("      if (idx >= 0) { drawCCn(idx, cx, y, color); cx += CCN_W + pad; }")
    lines.append("      p += 3;")
    lines.append("    } else p++;")
    lines.append("  }")
    lines.append("  return cx - x;")
    lines.append("}")
    lines.append("")
    lines.append("static int cityCnWidth(const char* s, int pad = 2) {")
    lines.append("  int n = 0;")
    lines.append("  for (const char* p = s; *p; ) {")
    lines.append("    if ((unsigned char)*p >= 0x80) { n++; p += 3; } else p++;")
    lines.append("  }")
    lines.append("  return n ? (n * CCN_W + (n - 1) * pad) : 0;")
    lines.append("}")
    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("written:", OUT_H, "chars:", len(CHARS))


if __name__ == "__main__":
    main()
