# -*- coding: utf-8 -*-
"""Generate 16x16 monochrome C bitmaps for Chinese calendar glyphs.

Renders each character with Windows SimHei at high resolution,
downscales to 16x16 grayscale, thresholds, and emits cn_font.h
(MSB-first, row-major, 32 bytes per glyph). Also prints an ASCII
preview so the glyphs can be verified before compiling.
"""
import os as _pathos
_HERE = _pathos.path.dirname(_pathos.path.abspath(__file__)).replace('\\', '/')
_TOOLS_DIR = _HERE + '/'
_SRC_DIR = _pathos.normpath(_HERE + '/../src').replace('\\', '/') + '/'
_BASE_DIR = _pathos.normpath(_HERE + '/..').replace('\\', '/')

from PIL import Image, ImageDraw, ImageFont

CHARS = "年月一二三四五六七八九十"
FONT_PATH = r"C:\Windows\Fonts\simhei.ttf"
OUT_H = _SRC_DIR + "cn_font.h"
GLYPH = 16

def render(ch):
    # render at 8x then downscale for smoother stroke weights
    big = GLYPH * 8
    img = Image.new("L", (big, big), 0)
    d = ImageDraw.Draw(img)
    # find a font size that fills the cell reasonably
    size = int(big * 0.86)
    font = ImageFont.truetype(FONT_PATH, size)
    d.text((big / 2, big / 2), ch, font=font, fill=255, anchor="mm")
    img = img.resize((GLYPH, GLYPH), Image.LANCZOS)
    px = img.load()
    bits = []
    for y in range(GLYPH):
        row = 0
        for x in range(GLYPH):
            if px[x, y] >= 128:
                row |= 1 << (15 - x)
                bits.append("#")
            else:
                bits.append(".")
        yield row
        bits.append("\n")
    print(ch + ":")
    print("".join(bits))

def main():
    names = {
        "年": "CN_NIAN", "月": "CN_YUE",
        "一": "CN_1", "二": "CN_2", "三": "CN_3", "四": "CN_4",
        "五": "CN_5", "六": "CN_6", "七": "CN_7", "八": "CN_8",
        "九": "CN_9", "十": "CN_10",
    }
    lines = []
    lines.append("// Auto-generated by tools/gen_cnfont.py -- 16x16 mono glyphs (SimHei)")
    lines.append("// chars: " + " ".join(CHARS))
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append("#define CN_GLYPH_W 16")
    lines.append("#define CN_GLYPH_H 16")
    lines.append("#define CN_GLYPH_BYTES 32")
    lines.append("")
    lines.append("enum { " + ", ".join(names[c] for c in CHARS) + " };")
    lines.append("")
    lines.append("static const uint8_t CN_GLYPHS[][CN_GLYPH_BYTES] PROGMEM = {")
    for ch in CHARS:
        rows = list(render(ch))
        body = []
        for r in rows:
            body.append("0x%02X,0x%02X" % ((r >> 8) & 0xFF, r & 0xFF))
        line = "  {" + ",".join(body) + "},"
        # annotate with the char comment (utf-8 in comment is safe)
        lines.append("  // " + ch)
        lines.append(line)
    lines.append("};")
    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("written:", OUT_H)

if __name__ == "__main__":
    main()
