# -*- coding: utf-8 -*-
"""Generate 16x16 monochrome C bitmaps for Chinese weather-page glyphs.

Renders each character with Windows SimHei at high resolution,
downscales to 16x16 grayscale, thresholds, and emits weather_cn.h
(MSB-first, row-major, 32 bytes per glyph). Also prints an ASCII
preview so the glyphs can be verified before compiling.

Usage:
  python tools/gen_weather_cn.py
"""
import os as _pathos
_HERE = _pathos.path.dirname(_pathos.path.abspath(__file__)).replace('\\', '/')
_TOOLS_DIR = _HERE + '/'
_SRC_DIR = _pathos.normpath(_HERE + '/../src').replace('\\', '/') + '/'
_BASE_DIR = _pathos.normpath(_HERE + '/..').replace('\\', '/')

from PIL import Image, ImageDraw, ImageFont

# 天气页要用到的全部汉字（去重），顺序即字模索引顺序
CHARS = "晴间多云阴雾毛毛雨冻小中大雪粒阵雷伴冰雹最高度风速未知无数据天气低湿"
FONT_PATH = r"C:\Windows\Fonts\simhei.ttf"
OUT_H = _SRC_DIR + "weather_cn.h"
GLYPH = 16


def render(ch):
    # render at 8x then downscale for smoother stroke weights
    big = GLYPH * 8
    img = Image.new("L", (big, big), 0)
    d = ImageDraw.Draw(img)
    size = int(big * 0.86)
    font = ImageFont.truetype(FONT_PATH, size)
    d.text((big / 2, big / 2), ch, font=font, fill=255, anchor="mm")
    img = img.resize((GLYPH, GLYPH), Image.LANCZOS)
    px = img.load()
    bits = []
    for y in range(GLYPH):
        row = 0
        for x in range(GLYPH):
            if px[x, y] >= 128:
                row |= 1 << (15 - x)
                bits.append("#")
            else:
                bits.append(".")
        yield row
        bits.append("\n")
    print(ch + ":")
    print("".join(bits))


def main():
    names = ["WCN_%d" % i for i in range(len(CHARS))]
    lines = []
    lines.append("// Auto-generated by tools/gen_weather_cn.py -- 16x16 mono glyphs (SimHei)")
    lines.append("// chars: " + " ".join(CHARS))
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append("#define WCN_W 16")
    lines.append("#define WCN_H 16")
    lines.append("#define WCN_BYTES 32")
    lines.append("")
    lines.append("enum { " + ", ".join(names) + " };")
    lines.append("")
    lines.append("static const uint8_t WCN_GLYPHS[][WCN_BYTES] PROGMEM = {")
    for ch in CHARS:
        rows = list(render(ch))
        body = []
        for r in rows:
            body.append("0x%02X,0x%02X" % ((r >> 8) & 0xFF, r & 0xFF))
        lines.append("  // " + ch)
        lines.append("  {" + ",".join(body) + "},")
    lines.append("};")
    lines.append("")
    # 汉字 -> 索引查找（UTF-8 三字节，存 PROGMEM）
    lines.append("static const char WCN_T[] PROGMEM = \"" + CHARS + "\";")
    lines.append("static int wcnFind(const char* u) {")
    lines.append("  for (int i = 0; i < (int)(sizeof(WCN_T) - 1) / 3; i++) {")
    lines.append("    if (u[0] == pgm_read_byte(&WCN_T[i * 3]) &&")
    lines.append("        u[1] == pgm_read_byte(&WCN_T[i * 3 + 1]) &&")
    lines.append("        u[2] == pgm_read_byte(&WCN_T[i * 3 + 2])) return i;")
    lines.append("  }")
    lines.append("  return -1;")
    lines.append("}")
    lines.append("")
    # 绘制单个字模（sprite 必须已 begin）
    lines.append("static void drawWCn(int idx, int x, int y, uint16_t color) {")
    lines.append("  for (int row = 0; row < WCN_H; row++) {")
    lines.append("    uint16_t bits = (uint16_t)pgm_read_byte(&WCN_GLYPHS[idx][row * 2]) << 8")
    lines.append("                  | pgm_read_byte(&WCN_GLYPHS[idx][row * 2 + 1]);")
    lines.append("    for (int col = 0; col < WCN_W; col++)")
    lines.append("      if (bits & (0x8000 >> col)) sprite.writeFastHLine(x + col, y + row, 1, color);")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    # 在 (x,y) 画一串纯汉字（UTF-8），返回占用宽度（含字间距）
    lines.append("static int drawCnStr(const char* s, int x, int y, uint16_t color, int pad = 2) {")
    lines.append("  int cx = x;")
    lines.append("  for (const char* p = s; *p; ) {")
    lines.append("    if ((unsigned char)*p >= 0x80) {            // 多字节（汉字）")
    lines.append("      int idx = wcnFind(p);")
    lines.append("      if (idx >= 0) { drawWCn(idx, cx, y, color); cx += WCN_W + pad; }")
    lines.append("      p += 3;")
    lines.append("    } else {")
    lines.append("      p++;                                       // 跳过 ASCII/控制字节")
    lines.append("    }")
    lines.append("  }")
    lines.append("  return cx - x;")
    lines.append("}")
    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("written:", OUT_H)


if __name__ == "__main__":
    main()
